// Autogenerated file using `pnpm load <path-to-json>`, don`t edit or delete
import '@/core/module/module.manager'
// Modules
import '@/modules/auth/saas'
import '@/modules/recording/recording'
import '@/modules/subscriptions/subscriptions'
// Services
import '@/services/auth/auth-supabase.service'
import '@/services/genesis/transcription.service'
import '@/services/subscriptions/subscriptions-supabase.service'