// Autogenerated file using `pnpm load <path-to-json>`, don`t edit or delete
import '@/core/module/module.manager'
// Modules
import '@/modules/auth/saas'
import '@/modules/recording/recording'
// Services
import '@/services/auth/auth-supabase.service'
import '@/services/api/genesis-api.service'