// Autogenerated file using `pnpm load <path-to-json>`, don`t edit or delete
import '@/core/module/module.manager'
// Modules
import '@/modules/auth/saas'
import '@/modules/recording/recording'
import '@/modules/subscriptions/subscriptions'
import '@/modules/templates/templates'
// Services
import '@/services/auth/auth-supabase.service'
import '@/services/genesis/transcription-mock.service'
import '@/services/subscriptions/subscriptions-supabase.service'
import '@/services/templates/supabase-templates.service'