const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_API_KEY = process.env.NEXT_PUBLIC_SUPABASE_KEY;
const TRANSCRIPTION_API = process.env.NEXT_PUBLIC_TRANSCRIPTION_API;

const config = {
  SUPABASE_URL,
  SUPABASE_API_KEY,
  TRANSCRIPTION_API,
};

export default config;
