export default {
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_API_KEY: process.env.NEXT_PUBLIC_SUPABASE_KEY,
  MEDICAL_TRANSCRIPTION_API_URL:
    process.env.NEXT_PUBLIC_MEDICAL_TRANSCRIPTION_API_URL,
};
